// ─────────────────────────────────────────────────────────────────────────────
// SocialConnect — Shared Demo Challenge Data
// Replace this file with an API call when the backend is ready.
// ─────────────────────────────────────────────────────────────────────────────

export type Priority = 'critical' | 'high' | 'medium' | 'low';
export type Status =
  | 'submitted'
  | 'ai_verified'
  | 'under_review'
  | 'assigned'
  | 'in_progress'
  | 'resolved';

export interface Challenge {
  id: string;
  title: string;
  category: string;
  description: string;
  fullDescription: string;
  location: string;
  district: string;
  priority: Priority;
  status: Status;
  date: string;         // ISO date string
  support: number;      // community support count
  submittedBy: string;
  proposedSolution: string;
  progress: number;     // 0-100
}

export const ALL_CATEGORIES = [
  'Infrastructure',
  'Environment',
  'Public Health',
  'Education',
  'Healthcare',
  'Water & Sanitation',
  'Waste Management',
  'Agriculture',
  'Transportation',
  'Energy',
  'Employment',
  'Digital Services',
  'Women & Child Welfare',
  'Accessibility',
] as const;

export const CHALLENGES: Challenge[] = [
  {
    id: 'CH-001',
    title: 'Severe Waterlogging During Monsoons on MG Road',
    category: 'Infrastructure',
    description: 'Every rainy season, the main junction floods entirely causing severe traffic blocks and health hazards for local residents. The existing drainage seems entirely blocked.',
    fullDescription: 'Every monsoon season, MG Road at the main junction floods to a depth of 2–3 feet within minutes of heavy rainfall. The existing drainage channels were last serviced over 8 years ago and are now completely blocked with silt and solid waste. The flooding causes severe traffic disruptions lasting 4–6 hours, damages roadside shops, and creates health hazards due to waterborne contamination. Over 12,000 residents and daily commuters are directly affected. Local authorities have acknowledged the issue but no remedial work has been initiated. An estimated 3 km of drainage network needs rehabilitation.',
    location: 'MG Road, Ward 12',
    district: 'Ranchi',
    priority: 'high',
    status: 'in_progress',
    date: '2024-09-01',
    support: 312,
    submittedBy: 'Resident Welfare Association, Ward 12',
    proposedSolution: "NIT Jamshedpur's Civil Engineering department has proposed a dual-channel drainage system with automated silt traps. Industry partner TATA Projects has agreed to provide construction supervision. Pilot covers 800m of road and is scheduled for completion by December 2024.",
    progress: 65,
  },
  {
    id: 'CH-002',
    title: 'Illegal Waste Dumping Near Lake Boundary',
    category: 'Environment',
    description: 'Unidentified vehicles are dumping industrial and construction waste near the lake premises overnight, severely polluting the water body.',
    fullDescription: "For the past 18 months, unidentified trucks have been illegally dumping industrial effluents and construction debris along a 1.2 km stretch of the lake's northern boundary between 10 PM and 3 AM. Water quality testing by a local NGO reveals heavy metal contamination at 4x permissible limits. The lake is a primary source of irrigation water for 6 surrounding villages and supports local fishing livelihoods for approximately 800 families. The Jharkhand State Pollution Control Board has been notified but enforcement remains inadequate.",
    location: 'North Lake Zone',
    district: 'Dhanbad',
    priority: 'critical',
    status: 'assigned',
    date: '2024-08-15',
    support: 198,
    submittedBy: 'Green Earth Foundation',
    proposedSolution: 'IIT (ISM) Dhanbad has proposed deploying IoT-based water quality sensors and installing CCTV surveillance cameras at 4 key access points. The data will feed into a real-time monitoring dashboard. Industry partner has agreed to fund camera hardware under CSR.',
    progress: 40,
  },
  {
    id: 'CH-003',
    title: 'Shortage of Essential Medical Services in Rural Clinic',
    category: 'Public Health',
    description: 'The closest hospital is 15 km away and the local clinic lacks essential supplies and staff, leaving over 5,000 residents vulnerable during emergencies.',
    fullDescription: 'The Govt. Primary Health Centre at Village Baridih serves a population of approximately 5,200 across 4 villages but operates with only 1 doctor (visiting twice a week), no resident nurse, and a chronic shortage of essential medicines including antibiotics, IV fluids, and diagnostic equipment. The nearest district hospital is 15 km away on an unpaved road that becomes impassable during monsoons. In the last year, 3 preventable maternal deaths have been reported. The PHC building itself is structurally compromised with a damaged roof and no running water.',
    location: 'Village Baridih, Block 3',
    district: 'Gumla',
    priority: 'critical',
    status: 'under_review',
    date: '2024-08-28',
    support: 276,
    submittedBy: 'Village Health Committee, Baridih',
    proposedSolution: 'Ranchi Medical College has proposed a Telemedicine-Assisted Primary Care model where MBBS interns are stationed at the PHC and specialist consultations happen via a secured video platform. Drug supply automation through a barcode-based inventory system is also proposed.',
    progress: 25,
  },
  {
    id: 'CH-004',
    title: 'Limited Digital Learning Facilities in Rural Schools',
    category: 'Education',
    description: 'Government schools in the block lack computers, internet access, and trained teachers, leaving students without 21st-century digital skills.',
    fullDescription: 'Twelve government middle schools in Khunti block serve approximately 8,400 students but have zero functional computers and no broadband internet connection. Under the National Education Policy 2020 mandate for digital literacy, these schools are severely non-compliant. Teachers have not received any ICT training since 2018. Students from these schools consistently underperform in state digital literacy assessments and face significant disadvantage when competing for higher education and employment. The block education office has flagged this for 3 consecutive years without resolution.',
    location: 'Khunti Block, 12 Schools',
    district: 'Khunti',
    priority: 'high',
    status: 'in_progress',
    date: '2024-07-20',
    support: 189,
    submittedBy: 'Block Education Officer, Khunti',
    proposedSolution: "BIT Mesra's Computer Science department has designed a Solar-Powered Computer Lab Kit — a self-contained unit with 10 refurbished computers, a Raspberry Pi-based local server, and offline educational content. Industry partner Wipro has committed 20 units under their CSR programme.",
    progress: 55,
  },
  {
    id: 'CH-005',
    title: 'Lack of Accessible Primary Healthcare Facility',
    category: 'Healthcare',
    description: 'Residents of 3 wards must travel over 12 km for any basic healthcare, leading to delayed treatments and preventable complications.',
    fullDescription: 'Wards 14, 15, and 16 of Deoghar Municipal Corporation, with a combined population of approximately 22,000 residents, do not have a single functioning primary health centre or dispensary within a 12 km radius. The nearest government hospital is understaffed and routinely turns away non-emergency cases. A 2023 community health survey found that 67% of residents delay seeking treatment due to travel costs and distance, resulting in a high incidence of complications from treatable conditions including diabetes, hypertension, and common infections.',
    location: 'Wards 14-16',
    district: 'Deoghar',
    priority: 'high',
    status: 'submitted',
    date: '2024-09-05',
    support: 143,
    submittedBy: 'Ward Councillor, Ward 14',
    proposedSolution: 'Pending university assignment. Likely solution involves a mobile health van service combined with a network of trained community health workers (CHWs) linked via a digital health record platform.',
    progress: 10,
  },
  {
    id: 'CH-006',
    title: 'Unsafe Drinking Water Supply in Rural Area',
    category: 'Water & Sanitation',
    description: 'Tap water in 6 villages tests positive for arsenic and iron at dangerous levels. Residents are forced to drink contaminated water or walk 5 km to alternative sources.',
    fullDescription: 'Government water supply pipelines serving 6 villages in Sahibganj block were installed in 1987 and have never been upgraded. Recent testing by the Jharkhand Jal Board found arsenic at 3.2x the permissible limit and iron at 8x the limit across all tested taps. Approximately 14,000 residents, including 2,200 children under 5, are consuming this water daily. The Block Development Officer received the test report in March 2024 but no remediation has commenced. Community members are spending up to 3 hours daily collecting relatively safer water from a borewell 5 km away.',
    location: 'Rajmahal Block, 6 Villages',
    district: 'Sahibganj',
    priority: 'critical',
    status: 'ai_verified',
    date: '2024-08-10',
    support: 341,
    submittedBy: 'Gram Panchayat, Rajmahal',
    proposedSolution: "NIT Jamshedpur's Environmental Engineering team is assessing a community-scale reverse osmosis and iron removal plant. A parallel proposal involves pipeline replacement using HDPE pipes rated for 25+ years. Funding is being sought under Jal Jeevan Mission.",
    progress: 20,
  },
  {
    id: 'CH-007',
    title: 'Open Waste Dumping Creating Health Hazards in Residential Area',
    category: 'Waste Management',
    description: 'An unofficial garbage dump has grown to over 2 acres on the edge of a residential colony, breeding mosquitoes and emitting toxic fumes from burning waste.',
    fullDescription: 'An unauthorised dumping ground on the outskirts of Sector 4 has been accumulating municipal solid waste for over 5 years. The site now covers approximately 2 acres and receives an estimated 8 tonnes of mixed waste daily from informal waste pickers and fly-tippers. Residents in a 500m radius report respiratory problems, skin rashes, and a 340% increase in mosquito-borne illness (dengue/malaria) compared to wards without a nearby dump. The site is on land earmarked for a community park under the city master plan. Three official complaints to the Municipal Corporation in 2023 received no response.',
    location: 'Sector 4, Near Community Park',
    district: 'Bokaro',
    priority: 'high',
    status: 'in_progress',
    date: '2024-07-05',
    support: 267,
    submittedBy: 'Sector 4 Residents Association',
    proposedSolution: 'BIT Mesra has proposed a 3-phase solution: Phase 1 — scientific capping and bio-remediation of the existing dump. Phase 2 — Decentralised waste processing unit with segregation and composting. Phase 3 — Smart bin network with IoT fill-level monitoring for the surrounding 8 wards.',
    progress: 60,
  },
  {
    id: 'CH-008',
    title: 'Water Scarcity Severely Affecting Crop Production for Local Farmers',
    category: 'Agriculture',
    description: 'Erratic rainfall and depleted groundwater have led to 3 consecutive seasons of crop failure for over 400 farming families, threatening livelihoods.',
    fullDescription: 'The Bero block of Ranchi district has experienced 3 consecutive years of below-normal monsoon rainfall. Groundwater levels have dropped by 14 feet over the past decade, making traditional hand-pump irrigation non-viable. Approximately 430 farming families, cultivating a combined 1,800 acres of rain-fed land, have suffered crop losses between 60–90% in each of the last 3 seasons. Farm household incomes have collapsed and rural-to-urban distress migration has accelerated. The local Krishi Vigyan Kendra has acknowledged the problem but lacks resources for a systematic intervention. Suicide among indebted farmers has been reported.',
    location: 'Bero Block, 8 Villages',
    district: 'Ranchi',
    priority: 'critical',
    status: 'in_progress',
    date: '2024-06-15',
    support: 389,
    submittedBy: 'Bero Farmers Collective',
    proposedSolution: "Jharkhand Rai University's Agriculture department has designed a micro-watershed management plan combining check dam construction, drip irrigation rollout, and shift to drought-resistant crop varieties. NABARD is being approached for capital subsidy and an industry agritech partner is providing precision farming tools.",
    progress: 70,
  },
  {
    id: 'CH-009',
    title: 'Poor Public Transport Connectivity in Peri-Urban Areas',
    category: 'Transportation',
    description: 'Residents of 5 newly-developed colonies have no bus service, forcing them to rely on expensive and unsafe private vehicles for daily commute.',
    fullDescription: '5 residential colonies developed under the Jharkhand Housing Board in the past 4 years, collectively housing approximately 28,000 residents, have no connection to the city public bus network. The nearest bus stop is 4.5 km away. Residents pay 3x the market rate for unregulated shared auto-rickshaws that are unsafe and unreliable. Morning and evening peak hours see significant congestion on a single approach road. Children attending city schools must leave before 5:30 AM. Pregnant women and elderly residents are particularly at risk with no accessible transport. The Ranchi Municipal Corporation Transport Wing has not responded to 4 petitions submitted over 18 months.',
    location: 'New Colony Zones A–E',
    district: 'Ranchi',
    priority: 'medium',
    status: 'assigned',
    date: '2024-08-01',
    support: 412,
    submittedBy: 'Resident Welfare Council, New Colonies',
    proposedSolution: "XLRI Jamshedpur's Operations Management team is modelling optimal bus route extensions using geographic demand mapping. The proposal includes a demand-responsive mini-bus service using a mobile app-based booking system as an interim measure before formal route integration.",
    progress: 35,
  },
  {
    id: 'CH-010',
    title: 'Frequent and Prolonged Power Outages in Rural Community',
    category: 'Energy',
    description: 'Villages in the Chakradharpur area experience 12–18 hours of power cuts daily, making livelihoods, education, and healthcare impossible.',
    fullDescription: 'Nine villages in the Chakradharpur administrative block receive electricity for an average of only 4–6 hours per day, primarily late at night. The transformer serving the area is overloaded and has failed 7 times in the past year. Students cannot study in the evenings, small businesses running refrigerators and machinery lose 60–70% of operational capacity, and the Primary Health Centre cannot maintain cold-chain storage for vaccines. The grid infrastructure was designed in 1974 for a population one-third of the current size. Petitions to JBVNL (Jharkhand Bijli Vitran Nigam Limited) over 3 years have yielded no transformer upgrade.',
    location: 'Chakradharpur Block, 9 Villages',
    district: 'West Singhbhum',
    priority: 'high',
    status: 'under_review',
    date: '2024-07-28',
    support: 298,
    submittedBy: 'Village Development Committee, Chakradharpur',
    proposedSolution: "IIT (ISM) Dhanbad's Electrical Engineering department has proposed a hybrid micro-grid solution: a 50kW solar PV installation with battery storage to provide reliable daytime power, complemented by a new dedicated transformer for night-time grid connectivity. Total estimated cost: ₹28 lakhs.",
    progress: 30,
  },
  {
    id: 'CH-011',
    title: 'Limited Skill-Based Employment Opportunities for Youth',
    category: 'Employment',
    description: 'Over 4,000 youth in the block are unemployed due to a mismatch between their educational qualifications and available local job market requirements.',
    fullDescription: "The Latehar district has an estimated 4,200 unemployed youth between ages 18–35 who have at least a Class 10 qualification but lack market-relevant vocational skills. The three nearest Industrial Training Institutes offer only 4 outdated trade courses (welding, electrical fitting, plumbing) with no placement linkages. Meanwhile, the district's growing manufacturing sector and service industry have 1,400 unfilled positions requiring skills in areas like CNC operation, IT support, solar panel installation, and healthcare assistance. A 2024 district employment survey confirmed a severe structural skills mismatch with no institutional mechanism to bridge it.",
    location: 'Latehar Urban & Peri-Urban',
    district: 'Latehar',
    priority: 'medium',
    status: 'in_progress',
    date: '2024-06-30',
    support: 156,
    submittedBy: 'District Employment Exchange, Latehar',
    proposedSolution: 'Jharkhand Rai University has partnered with 6 local manufacturing firms to design 12-week intensive skill modules in CNC operations, solar installation, and IT helpdesk. Industry partners provide hands-on training and guarantee interviews to graduates. NSDC (National Skill Development Corporation) certification is being pursued.',
    progress: 50,
  },
  {
    id: 'CH-012',
    title: 'Limited Access to Digital Government Services in Remote Areas',
    category: 'Digital Services',
    description: 'Residents of remote blocks are unable to access essential government e-services due to poor internet, no CSC centres, and low digital literacy.',
    fullDescription: 'Approximately 32,000 residents across 18 remote Gram Panchayats in Pakur district have no functioning Common Service Centre (CSC) within a 25 km radius. Accessing any digitally-mandated service — Aadhaar updates, ration card e-KYC, PM Kisan Samman Nidhi transfers, health insurance enrolment — requires an all-day trip to the district headquarters, with associated travel costs exceeding daily wages. Low-cost mobile data is available but internet speeds average 0.8 Mbps (insufficient for video-based services). Digital literacy assessment shows 91% of rural women and 74% of rural men cannot independently operate government portals. Large portions of entitled benefits remain unclaimed annually.',
    location: 'Pakur Block — 18 GPs',
    district: 'Pakur',
    priority: 'high',
    status: 'assigned',
    date: '2024-08-20',
    support: 167,
    submittedBy: 'District Collector Office, Pakur',
    proposedSolution: "BIT Mesra's IT department has designed a Panchayat Digital Service Van — a vehicle-mounted mobile CSC with a VSAT internet connection, biometric device, and a local services agent trained to assist residents. The van follows a weekly rotation schedule across all 18 GPs. The model is designed for scale across other underserved blocks.",
    progress: 40,
  },
  {
    id: 'CH-013',
    title: 'Lack of Safe Community Spaces for Women and Children',
    category: 'Women & Child Welfare',
    description: 'Urban slum clusters in the city lack safe, accessible spaces for women\'s livelihood activities and child development programmes.',
    fullDescription: 'Four urban slum clusters in Jamshedpur, collectively housing approximately 18,000 residents, have no designated women\'s self-help group meeting space, no crèche facility, and no children\'s learning centre. Women conducting income-generating activities (stitching, papad-making, handicrafts) must use their 100–120 sq. ft. living spaces, limiting productivity and excluding group-based livelihoods. Children between ages 3–6 have no access to Anganwadi services as the nearest centre is over 3 km away and has a waitlist of 140 children. The absence of safe, designated community spaces also prevents women from participating in awareness programmes, self-defence training, and legal aid camps.',
    location: 'Urban Slum Clusters A–D',
    district: 'East Singhbhum',
    priority: 'medium',
    status: 'in_progress',
    date: '2024-07-12',
    support: 221,
    submittedBy: 'Mahila Vikas Sangh, Jamshedpur',
    proposedSolution: "XLRI Jamshedpur's Social Enterprise division has proposed converting 4 underutilised government-owned plots (ranging from 1,000–1,500 sq. ft.) into Community Livelihood Centres. Each centre will house a crèche, an SHG workspace, a digital literacy corner, and a legal aid clinic. Design and build managed by student teams under faculty supervision.",
    progress: 55,
  },
  {
    id: 'CH-014',
    title: 'Lack of Accessible Public Infrastructure for Persons with Disabilities',
    category: 'Accessibility',
    description: 'Government buildings, roads, and public transport in the district capital remain inaccessible to persons with physical disabilities, violating RPWD Act 2016.',
    fullDescription: 'A district-wide audit conducted by a disability rights organisation found that 94% of government buildings in Giridih town lack functional ramps, 87% have no accessible restrooms, and 100% of public buses have no wheelchair access or audio announcements. The district court, civil hospital, collector\'s office, and main bus stand — facilities used by persons with disabilities on critical matters — are all fully inaccessible. This directly violates the Rights of Persons with Disabilities Act 2016 and the National Building Code accessibility provisions. An estimated 12,000 persons with disabilities in the district are effectively excluded from basic civic participation and access to justice. No compliance timeline has been set despite repeated representations to the Disability Welfare Department.',
    location: 'Giridih Town — Government Quarter',
    district: 'Giridih',
    priority: 'high',
    status: 'under_review',
    date: '2024-08-25',
    support: 134,
    submittedBy: 'Disability Rights Forum, Giridih',
    proposedSolution: 'NIT Jamshedpur\'s Architecture and Civil Engineering departments are conducting a Universal Design audit of 12 priority public buildings and proposing retrofit solutions. The project includes tactile pathway design, ramp construction specifications, accessible restroom retrofitting, and a wayfinding system for visually impaired persons.',
    progress: 20,
  },
];
